{'candidate_primary': ['CI/CD',
  'Docker',
  'Kubernetes',
  'LangChain',
  'LlamaIndex',
  'MLflow',
  'NLP',
  'Pandas',
  'PyTorch',
  'Python',
  'Spark',
  'TensorFlow'],
 'candidate_inferred': ['Airflow',
  'CI/CD Concepts',
  'Classic NLP',
  'FastAPI',
  'Github Actions',
  'GraphQL',
  'Redis',
  'scikit-learn'],
 'candidate_inferred_sec': ['AKS',
  'AML',
  'API Gateway',
  'Agents',
  'Airflow (orchestration)',
  'Azure',
  'Azure App Service',
  'Azure Cognitive Search',
  'Azure DevOps',
  'Azure Functions',
  'Bayesian NNs',
  'Bayesian Neural Nets',
  'BigQuery',
  'Boosting algorithms',
  'C++',
  'Cloud Build',
  'Cloud Run',
  'CloudWatch',
  'Cron Jobs',
  'Dagster',
  'Data Visualization',
  'Databricks',
  'DevOps',
  'Dockerized training/inference pipelines',
  'Document Routing',
  'EC2',
  'ETL/ELT pipelines',
  'Elasticsearch',
  'Functions',
  'GANs',
  'GKE',
  'Github',
  'GraphDB',
  'Hugging Face',
  'Hugging Face Inference API',
  'Hugging Face Trainer',
  'Human-in-the-Loop Pipelines',
  'Human-in-the-loop pipelines',
  'IAM',
  'IAM & Security',
  'Integration Tests',
  'Integration testing',
  'JavaScript',
  'Knowledge Graphs',
  'LLM-as-a-Judge',
  'Lambda',
  'LangGraph',
  'Langfuse',
  'Lora',
  'Monitor AWS',
  'Multi-query Expansion',
  'MySQL',
  'OCR pipelines',
  'Online training automation',
  'OpenAI/Gemini API',
  'PDFMiner',
  'PostgreSQL',
  'Prediction Intervals',
  'PyMuPDF',
  'Qdrant',
  'Redis Queue',
  'Reranking',
  'Rule-based Regex NLP',
  'S3',
  'SHAP',
  'SageMaker',
  'Snowflake',
  'Streamlit',
  'Tableau',
  'Tesseract',
  'Transformers',
  'Unit Tests',
  'Vector DB',
  'Vertex AI',
  'analytical thinking',
  'dbt',
  'document routing',
  'leadership',
  'mentorship',
  'multi-query expansion',
  'rapid learning',
  'rule-based NLP'],
 'matched_but_not_exact_report': {'Primary': ['CI/CD', 'NLP'],
  'Inferred': ['Airflow', 'Github Actions', 'GraphQL', 'Redis'],
  'Inferred_Secondary': ['Airflow', 'Hugging Face', 'Redis']},
 'missing_skills_report': {'Primary': ['AWS',
   'Kubeflow',
   'LLM',
   'NoSQL',
   'SQL'],
  'Inferred': ['Ansible',
   'ELK Stack',
   'Flask',
   'Gensim',
   'Grafana',
   'Helm',
   'HuggingFace Transformers',
   'Istio',
   'Jenkins',
   'Kafka',
   'Knative',
   'NLTK',
   'NumPy',
   'OpenCV',
   'Prefect',
   'Prometheus',
   'REST APIs',
   'RabbitMQ',
   'SciPy',
   'Scikit-learn',
   'Terraform'],
  'Inferred_Secondary': ['Airflow',
   'Annoy',
   'Ansible',
   'ArgoCD',
   'Azure ML',
   'BentoML',
   'Cassandra',
   'CuDF',
   'Dask',
   'Django',
   'Druid',
   'ELK Stack',
   'Evidently',
   'FAISS',
   'FastText',
   'Feast',
   'Flask',
   'Flink',
   'Gensim',
   'Google Cloud AI',
   'Grafana',
   'Great Expectations',
   'HNSW',
   'Hydra',
   'Hyperopt',
   'Jenkins',
   'Kafka',
   'Koalas',
   'MLlib',
   'Matplotlib',
   'Modin',
   'MongoDB',
   'NLTK',
   'Neo4j',
   'NumPy',
   'ONNX',
   'OpenAI',
   'Optuna',
   'Plotly',
   'Prefect',
   'Presto',
   'Prometheus',
   'Pulumi',
   'PySpark',
   'Ray',
   'Redis',
   'ScaNN',
   'SciPy',
   'Scikit-learn',
   'Seaborn',
   'Seldon',
   'Storm',
   'TensorRT',
   'Terraform',
   'Vaex',
   'Weights & Biases',
   'YAML',
   'spaCy']}}